#!/bin/sh

#This is a work in progress.  It should install the server components and register them correctly.  

# Set variables
directory='/opt/monitoring'

# Create program directory
mkdir -p $directory
cp -R server $directory

# Install pymysql
python3 -m pip install --target=$directory/server/ pymysql

chmod -R 755 $directory/server

sed -i "s,app_path = './',app_path = '/opt/monitoring/server/',g" $directory/server/web/server.py
sed -i "s,app_path = './',app_path = '/opt/monitoring/server/',g" $directory/server/collect.py
sed -i "s,app_path = './',app_path = '/opt/monitoring/server/',g" $directory/server/event.py
sed -i "s,cert_path = './certificates/',cert_path = '/opt/monitoring/server/certificates/',g" $directory/server/collect.py
sed -i "s,cert_path = './certificates/',cert_path = '/opt/monitoring/server/certificates/',g" $directory/server/web/server.py


# Write systemd service files

cat > /lib/systemd/system/mcserver.service <<EOF
[Unit]
Description=Linux Monitoring Collect Server Service
After=multi-user.target  

[Service]
Type=simple
ExecStart=/usr/bin/python3 /opt/monitoring/server/collect.py

[Install]
WantedBy=multi-user.target
EOF

cat > /lib/systemd/system/meserver.service <<EOF
[Unit]
Description=Linux Monitoring Event Server Service
After=multi-user.target

[Service]
Type=simple
ExecStart=/usr/bin/python3 /opt/monitoring/server/event.py

[Install]
WantedBy=multi-user.target
EOF

cat > /lib/systemd/system/mwserver.service <<EOF
[Unit]
Description=Linux Monitoring Web Server Service
After=multi-user.target

[Service]
WorkingDirectory=/opt/monitoring/server/
Type=simple
ExecStart=/usr/bin/python3 /opt/monitoring/server/start.py
Restart=always

[Install]
WantedBy=multi-user.target
EOF


# Set Permissions
chmod 644 /lib/systemd/system/mcserver.service
chmod 644 /lib/systemd/system/meserver.service
chmod 644 /lib/systemd/system/mwserver.service

# Enable service

systemctl daemon-reload

systemctl enable mcserver.service
systemctl enable meserver.service
systemctl enable mwserver.service

systemctl start mcserver.service
systemctl start meserver.service
systemctl start mwserver.service
