#!/bin/sh

# Script for configuring the monitoring agent to use systemd
# Default install directory is /opt/monitoring
# Default service account is monitoring

# Add service account
useradd -r -s /bin/false monitoring
# Delete service account
#userdel monitoring

mkdir -p /opt/monitoring/agent
cp agent.py /opt/monitoring/agent/agent.py
cp  settings.ini /opt/monitoring/agent/setting.ini
chown -R monitoring /opt/monitoring
chmod -R 755 /opt/monitoring/agent

echo "[Unit]" > /lib/systemd/system/magent.service
echo "Description=Linux Monitoring Agent Service" >> /lib/systemd/system/magent.service
echo "After=multi-user.target" >> /lib/systemd/system/magent.service
echo "\n" >> /lib/systemd/system/magent.service
echo "[Service]" >> /lib/systemd/system/magent.service
echo "Type=simple" >> /lib/systemd/system/magent.service
echo "ExecStart=/usr/bin/python3.7 /opt/monitoring/agent/agent.py" >> /lib/systemd/system/magent.service
echo "User=monitoring" >> /lib/systemd/system/magent.service
echo "\n" >> /lib/systemd/system/magent.service
echo "[Install]" >> /lib/systemd/system/magent.service
echo "WantedBy=multi-user.target" >> /lib/systemd/system/magent.service

chmod 644 /lib/systemd/system/magent.service
systemctl daemon-reload
systemctl enable magent.service
systemctl start magent.service
