# Generated by Django 2.1 on 2018-08-06 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mon_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentsystem',
            name='value',
        ),
    ]
