# Generated by Django 2.1 on 2018-08-06 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_app', '0002_remove_agentsystem_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentsystem',
            name='domain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
