# Generated by Django 2.0.7 on 2018-08-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_app', '0003_auto_20180805_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentsystem',
            name='osarchitecture',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='agentsystem',
            name='osbuild',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
