# Generated by Django 2.0.7 on 2018-08-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_app', '0004_auto_20180809_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsystem',
            name='ipaddress',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agentsystem',
            name='memory',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='agentsystem',
            name='osname',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='agentsystem',
            name='processors',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
