#!/bin/sh

# Set variables
user='monitoring'
directory='/opt/monitoring'
pythonver='python3'

# Add service account
#useradd -r -s /bin/false $user
# Delete service account
#userdel monitoring

# Create program directory
mkdir -p $directory/agent
cp agent.py $directory/agent/agent.py
cp  settings.ini $directory/agent/settings.ini
#chown -R monitoring $directory
chmod -R 755 $directory/agent

# Write systemd service file
cat > /lib/systemd/system/magent.service <<EOF
[Unit]
Description=Linux Monitoring Agent Service
After=multi-user.target

[Service]
Type=simple
ExecStart=/usr/bin/$pythonver $directory/agent/agent.py

[Install]
WantedBy=multi-user.target
EOF

# Set Permissions
chmod 644 /lib/systemd/system/magent.service

# Enable service
systemctl daemon-reload
systemctl enable magent.service
systemctl start magent.service
