#!/bin/sh

# This should install the server components and register them correctly.  
# You will still have to run the create database sql script in mysql or mariadb
# To use this file run: 
# chmod 755 mserver
# sudo ./mserver

# Set variables
directory='/opt/monitoring'
py_ver='python3.8'

# Create program directory
mkdir -p $directory
cp -R web $directory
cp -R services $directory
cp -R database $directory
cp -R certificates $directory
cp -R agents $directory

# Set up Python
$py_ver -m venv $directory/env
$directory/env/bin/$py_ver -m pip install pymysql flask gunicorn

# Write systemd service files

cat > /lib/systemd/system/mcserver.service <<EOF
[Unit]
Description=Linux Monitoring Collect Server Service
After=multi-user.target  

[Service]
Type=simple
ExecStart=$directory/env/bin/$py_ver /opt/monitoring/services/collect.py

[Install]
WantedBy=multi-user.target
EOF

cat > /lib/systemd/system/meserver.service <<EOF
[Unit]
Description=Linux Monitoring Event Server Service
After=multi-user.target

[Service]
Type=simple
ExecStart=$directory/env/bin/$py_ver /opt/monitoring/services/event.py

[Install]
WantedBy=multi-user.target
EOF

cat > /lib/systemd/system/mwserver.service <<EOF
[Unit]
Description=Linux Monitoring Web Server Service
After=multi-user.target

[Service]
WorkingDirectory=/opt/monitoring/web/
Type=simple
ExecStart=$directory/env/bin/gunicorn app:app
Restart=always

[Install]
WantedBy=multi-user.target
EOF


# Set Permissions
chmod 644 /lib/systemd/system/mcserver.service
chmod 644 /lib/systemd/system/meserver.service
chmod 644 /lib/systemd/system/mwserver.service

# Enable service

systemctl daemon-reload

systemctl enable mcserver.service
systemctl enable meserver.service
systemctl enable mwserver.service

systemctl start mcserver.service
systemctl start meserver.service
systemctl start mwserver.service
